# 使用官方 PHP 基础镜像（包含 FPM）
FROM php:8.2-fpm

#Maintainer
LABEL maintainer="wayixia@gmail.com"


# 安装 Nginx 和常用工具
RUN apt-get update && apt-get install -y \
        nginx \
        supervisor \
        curl \
        git \
        vim \
        certbot \
        python3-certbot-nginx \
        libfreetype6-dev \
	libjpeg62-turbo-dev \
        net-tools \
	libpng-dev


# 安装常用 PHP 扩展
RUN docker-php-ext-install mysqli pdo pdo_mysql opcache gd
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-enable mysqli

# 安装 Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# 添加 Xdebug 配置
RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# 安装 Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# 安装 Node.js
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# 配置 Nginx
COPY nginx_dev.conf /etc/nginx/nginx.conf


COPY supervisord_dev.conf  /etc/supervisor/conf.d/supervisord.conf

# 设置工作目录
WORKDIR /app

# 复制网站文件
COPY info.php /app/www/info.php

# 复制启动脚本并设置权限
COPY start_dev.sh /start.sh
RUN chmod +x /start.sh


# 暴露端口
EXPOSE 80 
#EXPOSE 443
#EXPOSE 3306

# 设置容器启动命令
# CMD ["/mysql_init.sh"]
CMD ["/start.sh"]

